url: https://dimitrivalax.github.io/
baseurl:

# Site settings
title: Dimitri Valax
email: dvalax.pro@gmail.com

description: 'Je suis développeur Mobile & Web Full-stack. mes compétences sont HTML CSS, javascript, PWA, Angular, React, Node.js, Ionic, Android, IOS'
lead: Bienvenue !
heading: Je suis développeur Mobile & Web Full-stack
button: Tu veux en savoir plus ?

# Team names, titles and social links
people:
  - name: Dimitri Valax
    pic: dimitri
    position: moi même !
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/dimitri-valax/
      - title: envelope
        url: mailto:dimitri@valax.fr

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dimitri-valax/
  - title: github
    url: http://github.com/dimitrivalax

# Postal address (add as many lines as necessary)
address:
  - line: 15 rue gabriel péri
  - line: 31000 toulouse

# Build settings
markdown: kramdown
permalink: pretty

# Su
contact_form_url: https://usydjvodljnjdviilloe.supabase.co/functions/v1/contact-form
supabase_anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzeWRqdm9kbGpuamR2aWlsbG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5OTE5MzgsImV4cCI6MjA5ODU2NzkzOH0.TqzTtO66CLSOkkbjhTv4reQUpPCU5IEj-cSKxERhIp4
