url: https://dimitrivalax.github.io/
baseurl:

# Site settings
title: Dimitri Valax
email: dvalax.pro@gmail.com
description: 'Je suis développeur Mobile & Web Full-stack. mes compétences sont HTML CSS, javascript, PWA, Angular, React, Node.js, Ionic, Android, IOS'
lead: Bienvenue !
heading: Je suis développeur Mobile & Web Full-stack
button: Tu veux en savoir plus ?

# Team names, titles and social links
people:
  - name: Lune bleue
    pic: lune-bleue-rose
    position: Echanger, travailler et se restaurer !!!
    social:
      - title: laptop
        url: https://lunebleue.coop/
      - title: linkedin
        url: https://www.linkedin.com/company/scic-lune-bleue/
      - title: facebook
        url: https://www.facebook.com/lunebleue.toulouse/
  - name: Dimitri Valax
    pic: dimitri
    position: moi même !
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/dimitri-valax-01b07b6
      - title: envelope
        url: mailto:dvalax.pro@gmail.com
  - name: Happy dev
    pic: happy-dev
    position: Réseau d'indépendants
    social:
      - title: laptop
        url: https://www.happy-dev.fr/
      - title: facebook
        url: https://www.facebook.com/HappydevToulouse/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dimitri-valax-01b07b6
  - title: twitter
    url: http://twitter.com/dimitrivalax
  - title: github
    url: http://github.com/dimitrivalax

# Postal address (add as many lines as necessary)
address:
  - line: 15 rue gabriel péri
  - line: 31000 toulouse

# Build settings
markdown: kramdown
permalink: pretty
